apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-ao2u
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-ao2u
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-ao2u
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-ao2u
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-ao2u
    spec:
      containers:
      - image: quay.io/qijing/ex-registry-bwof-tenant/appstudio/dc-metro-map-ao2u@sha256:85e0fc68e32bc692a43e268ab694b76fcd25cee2fe139f4f4e4a0b18d5f945df
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
