apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-ao2u
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/qijing/ex-registry-bwof-tenant/appstudio/dc-metro-map-ao2u@sha256:85e0fc68e32bc692a43e268ab694b76fcd25cee2fe139f4f4e4a0b18d5f945df
        name: my-nodejs
        resources: {}
status: {}
